namespace CodeForCoders.Commerce.Application.UseCases.Entitlement.ListStudentCourseAccess;

public interface IListStudentCourseAccess : IUseCase<ListStudentCourseAccessInput, StudentCourseAccessList>;
