// <auto-generated />
using System;
using CodeForCoders.Audit.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeForCoders.Audit.Infra.Data.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260924174803_RecordNonConformingAdministrativeActs")]
    partial class RecordNonConformingAdministrativeActs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit_access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeForCoders.Audit.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("AuthorType")
                        .HasColumnType("text")
                        .HasColumnName("autor_tipo");

                    b.Property<string>("Complement")
                        .HasColumnType("jsonb")
                        .HasColumnName("complemento");

                    b.Property<string>("Conformity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("conformidade");

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid")
                        .HasColumnName("fato_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("impressao_digital");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origem");

                    b.Property<DateTimeOffset?>("PracticedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("praticado_em");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.PrimitiveCollection<string[]>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("razoes");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("alvo_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("alvo_tipo");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Origin", "FactId")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_records_origem_fato_id");

                    b.HasIndex("TenantId", "PracticedOn")
                        .HasDatabaseName("ix_audit_records_tenant_praticado_em");

                    b.ToTable("audit_records", "audit_access", t =>
                        {
                            t.HasComment("Append-only audit evidence. UPDATE and DELETE are rejected by database trigger.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
