<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/CodeForCoders.BffStudent.Application/CodeForCoders.BffStudent.Application.csproj" />
    <ProjectReference Include="../../src/CodeForCoders.BffStudent.Domain/CodeForCoders.BffStudent.Domain.csproj" />
    <ProjectReference Include="../CodeForCoders.BffStudent.Tests.Common/CodeForCoders.BffStudent.Tests.Common.csproj" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
