using CodeForCoders.Identity.Application.UseCases;

namespace CodeForCoders.Identity.Application.UseCases.Accounts.RequestStudentAccountConfirmation;

public interface IRequestStudentAccountConfirmation : IUseCase<RequestStudentAccountConfirmationInput, RequestStudentAccountConfirmationOutput>;
