namespace CodeForCoders.Media.Application.UseCases.PlaybackSessions.RecordPlaybackProgress;

public interface IRecordPlaybackProgress : IUseCase<RecordPlaybackProgressInput, RecordPlaybackProgressOutput>;
