<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/CodeForCoders.Billing.Application/CodeForCoders.Billing.Application.csproj" />
    <ProjectReference Include="../../src/CodeForCoders.Billing.Domain/CodeForCoders.Billing.Domain.csproj" />
    <ProjectReference Include="../../src/CodeForCoders.Billing.Infra.Data/CodeForCoders.Billing.Infra.Data.csproj" />
    <ProjectReference Include="../CodeForCoders.Billing.Tests.Common/CodeForCoders.Billing.Tests.Common.csproj" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
