<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeForCoders.Billing.Application/CodeForCoders.Billing.Application.csproj" />
    <ProjectReference Include="../CodeForCoders.Billing.Contracts/CodeForCoders.Billing.Contracts.csproj" />
    <ProjectReference Include="../CodeForCoders.Billing.Infra.Data/CodeForCoders.Billing.Infra.Data.csproj" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Polly.Core" />
  </ItemGroup>
</Project>
