<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeForCoders.Commerce.Contracts/CodeForCoders.Commerce.Contracts.csproj" />
    <ProjectReference Include="../CodeForCoders.Commerce.Domain/CodeForCoders.Commerce.Domain.csproj" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>
</Project>
