<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeForCoders.Identity.Application/CodeForCoders.Identity.Application.csproj" />
    <ProjectReference Include="../CodeForCoders.Identity.Contracts/CodeForCoders.Identity.Contracts.csproj" />
    <ProjectReference Include="../CodeForCoders.Identity.Infra.Data/CodeForCoders.Identity.Infra.Data.csproj" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>
</Project>
