<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeForCoders.BffAdmin.Application/CodeForCoders.BffAdmin.Application.csproj" />
    <ProjectReference Include="../CodeForCoders.BffAdmin.Contracts/CodeForCoders.BffAdmin.Contracts.csproj" />
    <ProjectReference Include="../CodeForCoders.BffAdmin.Infra.Data/CodeForCoders.BffAdmin.Infra.Data.csproj" />
    <ProjectReference Include="../CodeForCoders.BffAdmin.Infra.Messaging/CodeForCoders.BffAdmin.Infra.Messaging.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
</Project>
