import { Button } from '@/components/ui/button';
import type { ShowcaseOffer } from '@/features/student-showcase/api/get-showcase-course';
import { formatAccessPeriod } from '@/features/student-showcase/utils/access-period';
import { formatPriceCents } from '@/features/student-showcase/utils/format-price';

type OfferOptionProps = {
  offer: ShowcaseOffer;
};

// Name comes from the school and is rendered as text; the period line is always generated by the platform.
// The purchase action arrives with the next slice (11.0): the option is already shown, without action yet.
export const OfferOption = ({ offer }: OfferOptionProps) => {
  const period = formatAccessPeriod(offer.accessPeriod);

  return (
    <div className="flex flex-col gap-3 rounded-lg border border-border p-4">
      <h3 className="font-heading text-base font-semibold leading-snug text-foreground">{offer.name}</h3>
      {period ? <p className="text-sm text-muted-foreground">{period}</p> : null}
      <p className="text-xl font-semibold text-foreground">{formatPriceCents(offer.priceCents)}</p>
      <Button aria-label={`Comprar ${offer.name}`} type="button">
        Comprar
      </Button>
    </div>
  );
};
